resources:
- name: runtime-og-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/runtime-og-ci.git
    branch: master

- name: app-autoscaler
  type: git
  source:
    uri: git@github.com:/cloudfoundry-incubator/app-autoscaler.git
    branch: develop
    private_key: {{autoscaler_key}}

- name: tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1566795"
    token: {{tracker_api_token}}

jobs:
- name: unit-tests
  max_in_flight: 1
  plan:
  - aggregate:
    - get: app-autoscaler
      trigger: true
    - get: runtime-og-ci
  - task: unit
    file: runtime-og-ci/autoscaler/tasks/autoscaler-unit-tests.yml
  - put: tracker
    params:
      repos:
        - app-autoscaler
- name: integration-tests
  max_in_flight: 1
  plan:
  - aggregate:
    - get: app-autoscaler
      passed: [unit-tests]
      trigger: true
    - get: runtime-og-ci
  - task: integration
    file: runtime-og-ci/autoscaler/tasks/integration-tests.yml
