---
platform: linux

image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.3-jdk-8}

inputs:
- name: app-autoscaler
- name: runtime-og-ci

run:
  path: runtime-og-ci/autoscaler/scripts/autoscaler-unit-tests.sh
