---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: runtime-og-ci
- name: app-autoscaler-release

run:
  path: runtime-og-ci/autoscaler/scripts/autoscaler-acceptance.sh
