---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: runtime-og-ci
- name: cf-release

run:
  path: runtime-og-ci/app-autoscaler/scripts/deploy-cf-release.sh
