---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: runtime-og-ci
- name: cf-release
- name: diego-release

outputs:
- name: generate-manifest-artifacts

run:
  path: runtime-og-ci/autoscaler/scripts/generate-manifests.sh

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
