---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: runtime-og-ci

run:
  path: runtime-og-ci/runtime-og/scripts/cats.sh
