---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: dea_next
- name: runtime-og-ci
- name: rootfs
- name: dea-hm-workspace

run:
  path: runtime-og-ci/runtime-og/scripts/dea-integration-tests.sh
