---
platform: linux

image_resource:
  type: docker-image
  source: {repository: runtimeog/ci_image, tag: latest}

inputs:
- name: dea_next
- name: runtime-og-ci

run:
  path: runtime-og-ci/scripts/dir_server-tests.sh
